// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebDevRepair.Migrations
{
    [DbContext(typeof(StockifyContext))]
    [Migration("20260106161319_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "H,��մ�mI��I8",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            Quantity = 15,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 2,
                            Quantity = 50,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 3,
                            Quantity = 30,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 4,
                            Quantity = 10,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 5,
                            Quantity = 25,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 7,
                            Quantity = 40,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 10,
                            Quantity = 100,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 1,
                            Quantity = 20,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 9,
                            ProductId = 4,
                            Quantity = 12,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 10,
                            ProductId = 5,
                            Quantity = 30,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 11,
                            ProductId = 6,
                            Quantity = 60,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 12,
                            ProductId = 8,
                            Quantity = 45,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 13,
                            ProductId = 9,
                            Quantity = 35,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 14,
                            ProductId = 10,
                            Quantity = 80,
                            WarehouseId = 2
                        });
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "High-performance laptop",
                            Name = "Laptop",
                            Price = 1200.00m,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Wireless mouse",
                            Name = "Mouse",
                            Price = 25.00m,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Mechanical keyboard",
                            Name = "Keyboard",
                            Price = 85.00m,
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "27-inch 4K monitor",
                            Name = "Monitor",
                            Price = 350.00m,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "Noise-cancelling headphones",
                            Name = "Headphones",
                            Price = 150.00m,
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 6,
                            Description = "7-port USB hub",
                            Name = "USB Hub",
                            Price = 45.00m,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 7,
                            Description = "1080p HD webcam",
                            Name = "Webcam",
                            Price = 60.00m,
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 8,
                            Description = "LED desk lamp",
                            Name = "Desk Lamp",
                            Price = 35.00m,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 9,
                            Description = "1TB external SSD",
                            Name = "External SSD",
                            Price = 120.00m,
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 10,
                            Description = "Adjustable phone stand",
                            Name = "Phone Stand",
                            Price = 15.00m,
                            SupplierId = 1
                        });
                });

            modelBuilder.Entity("Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactInfo = "contact@techsupply.com",
                            Name = "TechSupply Co."
                        },
                        new
                        {
                            Id = 2,
                            ContactInfo = "info@electrotrade.com",
                            Name = "ElectroTrade"
                        });
                });

            modelBuilder.Entity("Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 5000,
                            Location = "New York",
                            PasswordHash = "�\"��m�RԓW\r?�h%$"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 4000,
                            Location = "Los Angeles",
                            PasswordHash = "�+��	���D���zS�"
                        });
                });

            modelBuilder.Entity("Inventory", b =>
                {
                    b.HasOne("Product", "Product")
                        .WithMany("Inventories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Warehouse", "Warehouse")
                        .WithMany("Inventories")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.HasOne("Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("Warehouse", b =>
                {
                    b.Navigation("Inventories");
                });
#pragma warning restore 612, 618
        }
    }
}
